# Configuration for training the diffusion model

# Data configuration
data_path: "auxpath/train/rivaGan/diffusiondb/00001001111010001010110011101100"  # Path to the dataset folder

# Model configuration
diffusion_model: unet  # Name to the model
learning_rate: 1e-4  # Learning rate for optimizer
lr_scheduler: "linear"  # Learning rate scheduler, options: ["step", "cosine", "exponential"]
use_ema: False  # Whether to use Exponential Moving Average (EMA) for model parameters

# Training settings
train_batchsize: 32  # Batch size for training
train_num_steps: 500000  # Number of training steps
ema_update_every: 1  # Update EMA model every 'n' steps
ema_decay: 0.99  # EMA decay rate
num_samples: 25  # Number of samples to generate for evaluation
save_and_sample_every: 10000  # Save and sample every 'n' steps

# Fine-tuning configuration
resume_from: false  # Whether to resume training from a checkpoint
pretrained_ckp:   # Path to the pretrained checkpoint for fine-tuning

# Mixed precision and AMP (Automatic Mixed Precision) settings
amp: true  # Whether to use mixed precision training (AMP)

# Training duration
train_num: 5000 # Total number of sample in training set

# Results and output
results_folder: experiments  # Path where results will be saved
exp_name: ddim_hidden

# Other settings can be added as needed
